# Generated by Django 5.0.3 on 2024-03-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
