# Generated by Django 5.0.3 on 2024-03-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_testimonial_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
