# Generated by Django 5.0.3 on 2024-03-30 02:58

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_created_data_review_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
