# Generated by Django 5.0.3 on 2024-03-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(choices=[('kg', 'kilogram'), ('l', 'liter'), ('p', 'piece')], default='kg', max_length=10),
        ),
    ]
